# Generated by Django 5.0.2 on 2024-03-01 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Car", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="brand",
            new_name="Brand",
        ),
    ]
